name: Teams
version: '${project.version}'
main: io.github.cardsandhuskers.teams.Teams
api-version: '1.21'
depend: [PlayerPoints]
softdepend: [PlaceholderAPI]
authors: [ cardsandhuskers ]
description: Teams manager
commands:
  teamMenu:
    description: opens the team menu
    command: /<command>
  lockTeams:
    description: prevent changes to teams
    command: /<command>
  unlockTeams:
    description: prevent changes to teams
    command: /<command>
  teams:
    description: parent command for handling teams
    command: /<command>