name: Teams
version: '1.0-SNAPSHOT'
main: io.github.cardsandhuskers.teams.Teams
api-version: 1.19
depend: []
commands:
  team:
    description: opens the team menu
    command: /<command>
  lockTeams:
    description: prevent changes to teams
    command: /<command>
  unlockTeams:
    description: prevent changes to teams
    command: /<command>